//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recept {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recept() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Recept", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pizza sauce, Mozzarella, Parmesan cheese, ham, tomatoes, mushrooms and fresh herbs.
        /// </summary>
        internal static string d10 {
            get {
                return ResourceManager.GetString("d10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pizza sauce, cheese &quot;Emental&quot;, &quot;Cheder&quot;, &quot;Dor Blue&quot;and &quot;Parmesan&quot;.
        /// </summary>
        internal static string d11 {
            get {
                return ResourceManager.GetString("d11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pizza Quatro-stadzhioni &quot;leave no one indifferent. A variety of ingredients to satisfy customers with different tastes. 1 / 4 pizza &quot;Monica &quot;, 1 / 4 pizza &quot;Francesca&quot;, 1 / 4 pizza &quot;Adriano&quot; and 1 / 4 - onions, olives, tomatoes and mushrooms.
        /// </summary>
        internal static string d12 {
            get {
                return ResourceManager.GetString("d12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как descr10.
        /// </summary>
        internal static string d13 {
            get {
                return ResourceManager.GetString("d13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как descr11.
        /// </summary>
        internal static string d14 {
            get {
                return ResourceManager.GetString("d14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как descr12.
        /// </summary>
        internal static string d15 {
            get {
                return ResourceManager.GetString("d15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Coca-Cola is a carbonated soft drink sold in the stores.
        /// </summary>
        internal static string d16 {
            get {
                return ResourceManager.GetString("d16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как BonAqua - this is an example of crystal purity and a unique freshness. Is a highly.
        /// </summary>
        internal static string d17 {
            get {
                return ResourceManager.GetString("d17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Sprite is a transparent, lemon-lime flavored, caffeine free soft drink.
        /// </summary>
        internal static string d18 {
            get {
                return ResourceManager.GetString("d18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Coca-Cola is a carbonated soft drink sold in the stores.
        /// </summary>
        internal static string d19 {
            get {
                return ResourceManager.GetString("d19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как BonAqua - this is an example of crystal purity and a unique freshness. Is a highly.
        /// </summary>
        internal static string d20 {
            get {
                return ResourceManager.GetString("d20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Sprite is a transparent, lemon-lime flavored, caffeine free soft drink.
        /// </summary>
        internal static string d21 {
            get {
                return ResourceManager.GetString("d21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Refuel kiwi mousse, whipped cream, sprinkled with walnuts. Comes with a sticker with caramel, which you can pour over salad on their own..
        /// </summary>
        internal static string d22 {
            get {
                return ResourceManager.GetString("d22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pizza, sauce, Mozzarella, tomatoes, basil and oregano.
        /// </summary>
        internal static string d4 {
            get {
                return ResourceManager.GetString("d4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pizza, sauce, Mozzarella, mushrooms, peppers, broccoli, capers, tomatoes, olives, onions, corn and  herbs.
        /// </summary>
        internal static string d5 {
            get {
                return ResourceManager.GetString("d5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pizza sauce, Mozzarella, pineapple, ham, tomatoes and herbs.
        /// </summary>
        internal static string d6 {
            get {
                return ResourceManager.GetString("d6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pizza sauce, Mozzarella, sausage hunting double, Bulgarian pepper, jalapenos and BBQ Sauce.
        /// </summary>
        internal static string d7 {
            get {
                return ResourceManager.GetString("d7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pizza sauce, Mozzarella, chicken, pineapple, jalapeno.
        /// </summary>
        internal static string d8 {
            get {
                return ResourceManager.GetString("d8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pizza sauce, Mozzarella, ham, salami, tomatoes, mushrooms.
        /// </summary>
        internal static string d9 {
            get {
                return ResourceManager.GetString("d9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Daniela.
        /// </summary>
        internal static string r10 {
            get {
                return ResourceManager.GetString("r10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Kvatro formaji.
        /// </summary>
        internal static string r11 {
            get {
                return ResourceManager.GetString("r11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Kvatro strajioni.
        /// </summary>
        internal static string r12 {
            get {
                return ResourceManager.GetString("r12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как recept10.
        /// </summary>
        internal static string r13 {
            get {
                return ResourceManager.GetString("r13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как recept11.
        /// </summary>
        internal static string r14 {
            get {
                return ResourceManager.GetString("r14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как recept12.
        /// </summary>
        internal static string r15 {
            get {
                return ResourceManager.GetString("r15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Coca-cola.
        /// </summary>
        internal static string r16 {
            get {
                return ResourceManager.GetString("r16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Bonaqua.
        /// </summary>
        internal static string r17 {
            get {
                return ResourceManager.GetString("r17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Sprite.
        /// </summary>
        internal static string r18 {
            get {
                return ResourceManager.GetString("r18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Coca-cola.
        /// </summary>
        internal static string r19 {
            get {
                return ResourceManager.GetString("r19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Bonaqua.
        /// </summary>
        internal static string r20 {
            get {
                return ResourceManager.GetString("r20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Sprite.
        /// </summary>
        internal static string r21 {
            get {
                return ResourceManager.GetString("r21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Fruit Fantasy.
        /// </summary>
        internal static string r22 {
            get {
                return ResourceManager.GetString("r22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Margarita.
        /// </summary>
        internal static string r4 {
            get {
                return ResourceManager.GetString("r4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Breakfast Laura.
        /// </summary>
        internal static string r5 {
            get {
                return ResourceManager.GetString("r5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Monica.
        /// </summary>
        internal static string r6 {
            get {
                return ResourceManager.GetString("r6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Sergio.
        /// </summary>
        internal static string r7 {
            get {
                return ResourceManager.GetString("r7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Domenika.
        /// </summary>
        internal static string r8 {
            get {
                return ResourceManager.GetString("r8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Francheska.
        /// </summary>
        internal static string r9 {
            get {
                return ResourceManager.GetString("r9", resourceCulture);
            }
        }
    }
}
