//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recept {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recept() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Recept", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza sauce, Mozzarella, Parmesan cheese, ham, tomatoes, mushrooms and fresh herbs.
        /// </summary>
        internal static string d10 {
            get {
                return ResourceManager.GetString("d10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza sauce, cheese &quot;Emental&quot;, &quot;Cheder&quot;, &quot;Dor Blue&quot;and &quot;Parmesan&quot;.
        /// </summary>
        internal static string d11 {
            get {
                return ResourceManager.GetString("d11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza Quatro-stadzhioni &quot;leave no one indifferent. A variety of ingredients to satisfy customers with different tastes. 1 / 4 pizza &quot;Monica &quot;, 1 / 4 pizza &quot;Francesca&quot;, 1 / 4 pizza &quot;Adriano&quot; and 1 / 4 - onions, olives, tomatoes and mushrooms.
        /// </summary>
        internal static string d12 {
            get {
                return ResourceManager.GetString("d12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descr10.
        /// </summary>
        internal static string d13 {
            get {
                return ResourceManager.GetString("d13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descr11.
        /// </summary>
        internal static string d14 {
            get {
                return ResourceManager.GetString("d14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descr12.
        /// </summary>
        internal static string d15 {
            get {
                return ResourceManager.GetString("d15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coca-Cola is a carbonated soft drink sold in the stores.
        /// </summary>
        internal static string d16 {
            get {
                return ResourceManager.GetString("d16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonAqua - this is an example of crystal purity and a unique freshness. Is a highly.
        /// </summary>
        internal static string d17 {
            get {
                return ResourceManager.GetString("d17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite is a transparent, lemon-lime flavored, caffeine free soft drink.
        /// </summary>
        internal static string d18 {
            get {
                return ResourceManager.GetString("d18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coca-Cola is a carbonated soft drink sold in the stores.
        /// </summary>
        internal static string d19 {
            get {
                return ResourceManager.GetString("d19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonAqua - this is an example of crystal purity and a unique freshness. Is a highly.
        /// </summary>
        internal static string d20 {
            get {
                return ResourceManager.GetString("d20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite is a transparent, lemon-lime flavored, caffeine free soft drink.
        /// </summary>
        internal static string d21 {
            get {
                return ResourceManager.GetString("d21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuel kiwi mousse, whipped cream, sprinkled with walnuts. Comes with a sticker with caramel, which you can pour over salad on their own..
        /// </summary>
        internal static string d22 {
            get {
                return ResourceManager.GetString("d22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza, sauce, Mozzarella, tomatoes, basil and oregano.
        /// </summary>
        internal static string d4 {
            get {
                return ResourceManager.GetString("d4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza, sauce, Mozzarella, mushrooms, peppers, broccoli, capers, tomatoes, olives, onions, corn and  herbs.
        /// </summary>
        internal static string d5 {
            get {
                return ResourceManager.GetString("d5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza sauce, Mozzarella, pineapple, ham, tomatoes and herbs.
        /// </summary>
        internal static string d6 {
            get {
                return ResourceManager.GetString("d6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza sauce, Mozzarella, sausage hunting double, Bulgarian pepper, jalapenos and BBQ Sauce.
        /// </summary>
        internal static string d7 {
            get {
                return ResourceManager.GetString("d7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza sauce, Mozzarella, chicken, pineapple, jalapeno.
        /// </summary>
        internal static string d8 {
            get {
                return ResourceManager.GetString("d8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pizza sauce, Mozzarella, ham, salami, tomatoes, mushrooms.
        /// </summary>
        internal static string d9 {
            get {
                return ResourceManager.GetString("d9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daniela.
        /// </summary>
        internal static string r10 {
            get {
                return ResourceManager.GetString("r10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvatro formaji.
        /// </summary>
        internal static string r11 {
            get {
                return ResourceManager.GetString("r11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kvatro strajioni.
        /// </summary>
        internal static string r12 {
            get {
                return ResourceManager.GetString("r12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recept10.
        /// </summary>
        internal static string r13 {
            get {
                return ResourceManager.GetString("r13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recept11.
        /// </summary>
        internal static string r14 {
            get {
                return ResourceManager.GetString("r14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recept12.
        /// </summary>
        internal static string r15 {
            get {
                return ResourceManager.GetString("r15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coca-cola.
        /// </summary>
        internal static string r16 {
            get {
                return ResourceManager.GetString("r16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonaqua.
        /// </summary>
        internal static string r17 {
            get {
                return ResourceManager.GetString("r17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite.
        /// </summary>
        internal static string r18 {
            get {
                return ResourceManager.GetString("r18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coca-cola.
        /// </summary>
        internal static string r19 {
            get {
                return ResourceManager.GetString("r19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonaqua.
        /// </summary>
        internal static string r20 {
            get {
                return ResourceManager.GetString("r20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprite.
        /// </summary>
        internal static string r21 {
            get {
                return ResourceManager.GetString("r21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit Fantasy.
        /// </summary>
        internal static string r22 {
            get {
                return ResourceManager.GetString("r22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margarita.
        /// </summary>
        internal static string r4 {
            get {
                return ResourceManager.GetString("r4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast Laura.
        /// </summary>
        internal static string r5 {
            get {
                return ResourceManager.GetString("r5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monica.
        /// </summary>
        internal static string r6 {
            get {
                return ResourceManager.GetString("r6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sergio.
        /// </summary>
        internal static string r7 {
            get {
                return ResourceManager.GetString("r7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domenika.
        /// </summary>
        internal static string r8 {
            get {
                return ResourceManager.GetString("r8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francheska.
        /// </summary>
        internal static string r9 {
            get {
                return ResourceManager.GetString("r9", resourceCulture);
            }
        }
    }
}
